[package]
name = "heisenberg"
version = "0.2.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
hora = "0.1.1"
ngt-sys = "1.14.8"
rocksdb = "0.20.1"
serde = "1.0.162"
serde_json = "1.0.96"
thiserror = "1.0.40"
